apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "redis-pod-labeler.clusterrolebinding" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "redis-pod-labeler.name" . }}
    helm.sh/chart: {{ include "redis-pod-labeler.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "redis-pod-labeler.clusterrole" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "redis-pod-labeler.serviceaccount" . }}
    namespace: {{ .Values.namespace }}
