kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
  {{- include "mongo-pod-labeler.labels" . | nindent 4 }}
  name: {{ include "mongo-pod-labeler.clusterrole" . }}
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods"]
    verbs: ["get", "patch", "list"]
