name: cratedb
apiVersion: v2
version: 2.0.1
appVersion: 4.4.1
description: A Helm chart for CrateDB ( CrateDB is a distributed SQL database built on top of a NoSQL foundation)
type: application
home: https://crate.io
sources:
  - https://github.com/crate/crate
maintainers:
  - name: hmdmph
    email: hmdmph@gmail.com
icon: https://raw.githubusercontent.com/crate/crate/master/blackbox/docs/_static/crate-logo.png

